schema = 3

[mod]
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.0"
    hash = "sha256-zNSuzjr5n7zhK8VOciSigLMfbnHbmyzsWdTcMlV1kjQ="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.5"
    hash = "sha256-pyfTIu1fx6cGYHhm+yi8YP2TgERnnqKRjqSV7WGb1Yk="
  [mod."github.com/iancoleman/strcase"]
    version = "v0.2.0"
    hash = "sha256-sjzaiANgbiiT9+xh09AwcQGQMGYNrMGiPzDl8L+x7mU="
  [mod."github.com/kr/fs"]
    version = "v0.1.0"
    hash = "sha256-+Cjz0rGmdNIV1QL4z8h7JAjHATa5pKndwSnD1M0J74c="
  [mod."github.com/lyft/protoc-gen-star"]
    version = "v0.6.0"
    hash = "sha256-eKTelMcBO7y8jneAWS1ZAbLQ0aDeL7lh6k5BO5rlb1U="
  [mod."github.com/pkg/errors"]
    version = "v0.8.1"
    hash = "sha256-oe3iddfoLRwpC3ki5fifHf2ZFprtg99iNak50shiuDw="
  [mod."github.com/pkg/sftp"]
    version = "v1.10.1"
    hash = "sha256-F0KnCYQ8sp3ptwueureBomSGTlnAa1h4L5BL2mSkhkc="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/spf13/afero"]
    version = "v1.6.0"
    hash = "sha256-ZzzshKZRvdo9JlPlhJ7VVymGfRSvP8XIY7fF2D24KHo="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.0"
    hash = "sha256-az0Vd4MG3JXfaYbj0Q6AOmNkrXgmXDeQm8+BBiDXmdA="
  [mod."github.com/stretchr/testify"]
    version = "v1.6.1"
    hash = "sha256-GwrZr9lU8698GFal0l/sFQ/TYP/eQIeNnnYJWpe3/IE="
  [mod."github.com/yuin/goldmark"]
    version = "v1.3.5"
    hash = "sha256-3U69JkjvNLU9PZwgrjlIzhTPeFWbgz127BGKFKWDOSM="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20191011191535-87dc89f01550"
    hash = "sha256-T0CaT5ri68osnd9VdNTZ0Ys+exaVbX4iC8MN60UNkXw="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20210508222113-6edffad5e616"
    hash = "sha256-U4o4PZ8KRpwbUN+E0VwewWNCiK5OGeBIpAMLJEbO9Ng="
  [mod."golang.org/x/mod"]
    version = "v0.5.0"
    hash = "sha256-damNokM4TXu0CM0ts35eW+lKSv7KaqOINYNzEj1fkpw="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20210813160813-60bc85c4be6d"
    hash = "sha256-cO1nZaaCgY3645SbF1O6EcJxzjBQHf16UdTv11b7evc="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20210220032951-036812b2e83c"
    hash = "sha256-qyBoAsnVWZyQM7UkJ573EjijMHK0q5mVoY/o4a8Agr4="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20210816183151-1e6c022a8912"
    hash = "sha256-vmDO4qXAa1XZmqkqSZLgZdWyYcHBrulRkT2lZW8PAYw="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20201126162022-7de9c90e9dd1"
    hash = "sha256-ykpqi1F7Yzo1BVwuG0nbQOZnK0qevcCD2xqbXbsoQq0="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."golang.org/x/tools"]
    version = "v0.1.5"
    hash = "sha256-j8lPgQVnXOzhQMrsXrkN1I+a5SFCYFGhHLk+X6Ia090="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/protobuf"]
    version = "v1.27.1"
    hash = "sha256-klLGFG4InPHIBDgisRph7H/02D5rBVx0ho9rZCRyLbk="
  [mod."gopkg.in/check.v1"]
    version = "v0.0.0-20161208181325-20d25e280405"
    hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.2"
    hash = "sha256-SjNLmGSxoYabOi/zdjymW3mSgaxaS39btBQ3/aUIkgc="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0-20200313102051-9f266ea9e77c"
    hash = "sha256-ZXiVLum4UY7Xg2LUMJOk3m248lOrab5FBxWU9emIaq0="
